CREATE PROCEDURE [dbo].[USP_INSERT_PRODUCT]
	@NAME VARCHAR(40),
	@DESCRIPTION VARCHAR(MAX),
	@PRICE DECIMAL
AS
	SET NOCOUNT ON;

	INSERT INTO [dbo].[Products]
	VALUES
	(
		@NAME,
		@DESCRIPTION,
		@PRICE
	);

	SELECT * FROM [dbo].[Products]
	WHERE ID = (SELECT SCOPE_IDENTITY())